---
apiVersion: extensions/v1beta1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: bitbucket-slack-bot
  namespace: monitoring
  labels:
    app: bitbucket-slack-bot
    version: "{{.Version}}"
    team: "{{.Team}}"
spec:
  replicas: {{ .Config "replicas" }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: bitbucket-slack-bot
  template:
    metadata:
      labels:
        app: bitbucket-slack-bot
        version: "{{.Version}}"
        team: "{{.Team}}"
    spec:
      imagePullSecrets:
      - name: fortnox-kube-pull-secret
      containers:
      - name: bitbucket-slack-bot
        image: "quay.io/fortnox/{{.ServiceName}}:{{.Version}}"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 3
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 3
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 200m
            memory: 100Mi
        ports:
        - containerPort: 8080
        env:
          - name: CONFIG_LOG_FORMAT
            value: "json"
          - name: CONFIG_LOG_LEVEL
            value: "error"
          - name: CONFIG_BITBUCKETURL
            valueFrom:
              configMapKeyRef:
                name: bitbucket-slack-bot
                key: bitbucket.url
          - name: CONFIG_BITBUCKETUSER
            valueFrom:
              secretKeyRef:
                name: bitbucket-slack-bot
                key: bitbucket.username
          - name: CONFIG_BITBUCKETPASSWORD
            valueFrom:
              secretKeyRef:
                name: bitbucket-slack-bot
                key: bitbucket.password
          - name: CONFIG_TOKEN
            valueFrom:
              secretKeyRef:
                name: bitbucket-slack-bot
                key: slack.token



